[build]
  command = "pip install -r requirements.txt"
  publish = "static"

[[redirects]]
  from = "/*"
  to = "/templates/index.html"
  status = 200

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"